### ISSUE TITLE
Database is failing due to upstream job failure.

### ISSUE THREAD

**Issue by bbourqu** [oneops/setup#71]
Creating a new setup with vagrant-centos7 is causing an issue on cms db install:
```==> default: Initializing DB..
==> default: tar (child): cms-db-pkg-continuous.tar.gz: Cannot open: No such file or directory
==> default: tar (child): Error is not recoverable: exiting now```

I see it called from https://github.com/oneops/dev-tools/blob/master/setup-scripts/init_db.sh#L6 
 
it looks to be coming from here https://github.com/oneops/build-wf/blob/master/jobs/cms-db-package/config.xml
 
```==> default: waiting jenkins build job to complete
==> default: waiting jenkins build job to complete
==> default: build failed, please check jenkins log, or go to http://localhost:30001```

`app` is failing from an upstream job with the following:
```net-http-persistent-3.0.0 requires ruby version ~> 2.1, which is incompatible
with the current version, ruby 2.0.0p598
Build step 'Execute shell' marked build as failure```

**Comment by ighouri** [comment]
@bbourqu this has been recently fixed by Lev here https://github.com/oneops/display/commit/a414116216c473940d74670d8459f5cf34e13cd4

**Comment by bbourqu** [comment]
pulled in all changes this morning and rebuilt.  `app` is still failing but for a different reason:

```shell
Fetching gem metadata from http://rubygems.org/............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies....
Using rake 11.3.0
Using bundler 1.13.3
Bundler::GemspecError: Could not read gem at
/usr/local/share/gems/cache/multi_json-1.12.1.gem. It may be corrupted.
An error occurred while installing multi_json (1.12.1), and Bundler cannot
continue.
Make sure that `gem install multi_json -v '1.12.1'` succeeds before bundling.
Build step 'Execute shell' marked build as failure```

I'll try to rebuild again but we should check on this error

**Comment by bbourqu** [comment]
Additional gem versions that are also causing issues

```shell
Fetching gem metadata from http://rubygems.org/............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies....
Using rake 11.3.0
Using bundler 1.13.3
Bundler::GemspecError: Could not read gem at
/usr/local/share/gems/cache/multi_json-1.12.1.gem. It may be corrupted.
An error occurred while installing multi_json (1.12.1), and Bundler cannot
continue.
Make sure that `gem install multi_json -v '1.12.1'` succeeds before bundling.
Build step 'Execute shell' marked build as failure
...
==> default: ERROR:  Error installing /home/oneops/dist/oneops/dist/oneops-admin-1.0.0.gem:
==> default:    rack requires Ruby version >= 2.2.2.
```

**Comment by ighouri** [comment]
@bbourqu How did you pulled in all the latest changes this morning ?
